# Site settings
title: Ben427's Portfolio
subtitle: 
email: b.bordofsky@gmail.com
description: The portfolio for Ben427
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/Ben427/
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/benbordofsky/
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
exclude: - vendor